# Generated by Django 4.1.2 on 2022-10-16 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000000)),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('category', models.CharField(choices=[('драма', 'ДРАМА'), ('комедия', 'КОМЕДИЯ'), ('эротика', 'ЭРОТИКА'), ('мюзиклы', 'МЮЗИКЛЫ'), ('триллер', 'ТРИЛЛЕР'), ('биографии', 'БИОГРАФИИ'), ('военные', 'ВОЕННЫЕ'), ('приключения', 'ПРИКЛЮЧЕНИЯ'), ('ужасы', 'УЖАСЫ'), ('спортивные', 'СПОРТИВНЫЕ')], max_length=20)),
                ('serial', models.CharField(choices=[('зарубежные', 'ЗАРУБЕЖНЫЕ'), ('турецкие', 'ТУРЕЦКИЕ'), ('русские', 'РУССКИЕ'), ('мультсериалы', 'МУЛЬТСЕРИАЛЫ'), ('дорамы', 'ДОРАМЫ'), ('аниме', 'АНИМЕ')], default='', max_length=20)),
                ('language', models.CharField(choices=[('американские', 'АМЕРИКАНСКИЕ'), ('турецкие', 'ТУРЕЦКИЕ'), ('российские', 'РОССИЙСКИЕ'), ('индийские', 'ИНДИЙСКИЕ'), ('украинские', 'УКРАИНСКИЕ'), ('французские', 'ФРАНЦУЗСКИЕ'), ('казахстанские', 'КАЗАХСТАНСКИЕ')], max_length=20)),
                ('status', models.CharField(choices=[('RA', 'НЕДАВНО ДОБАВЛЕННЫЙ'), ('MW', 'НАИБОЛЬШЕЕ КОЛИЧЕСТВО ПРОСМОТРОВ'), ('TR', 'САМЫЕ ПОПУЛЯРНЫЕ')], max_length=6)),
                ('cast', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('views_count', models.IntegerField(default=0)),
                ('movie_trailer', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=1)),
                ('link', models.URLField()),
                ('movie', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_link', to='kinogo.movie')),
            ],
        ),
    ]
